In [884]:
# Import libary
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [885]:
# Load Data
df = pd.read_csv(r"D:\End to End Project\Healthcare_Data_Cleaning_Project\hospital_data_unclean.csv")

In [886]:
df.head()

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,NaN,30.0,M,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,LEsliE tErrY,62.0,M,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,dAnnY SMiTH,76.0,FEMALE,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,ADRIeNNe bELL,43.0,FEMALE,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn

In [887]:
df.shape

(55505, 15)

In [888]:
df.describe()

                age   room_number
count  51065.000000  51064.000000
mean      51.576207    301.074554
std       19.591399    115.264773
min       13.000000    101.000000
25%       35.000000    202.000000
50%       52.000000    302.000000
75%       68.000000    400.000000
max       89.000000    500.000000

In [889]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55505 entries, 0 to 55504
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                51065 non-null  object
 1   age                 51065 non-null  float64
 2   gender              51065 non-null  object
 3   blood type          51065 non-null  object
 4   medical_condition   51065 non-null  object
 5   date_of_admission   51065 non-null  object
 6   doctor              51065 non-null  object
 7   hospital            51064 non-null  object
 8   insurance_provider  51063 non-null  object
 9   billing_amount      51065 non-null  object
 10  room_number         51064 non-null  float64
 11  admission_type      51065 non-null  object
 12  discharge_date      51064 non-null  object
 13  medication          51065 non-null  object
 14  test_results        51065 non-null  object
dtypes: float64(2), object(13)
memory usage: 6.4+ MB

In [890]:
df.isna()

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
55501,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55502,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
55503,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
55504,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False

In [891]:
df.isna().sum()

name                  4440
age                   4440
gender                4440
blood type            4440
medical_condition     4440
date_of_admission     4440
doctor                4440
hospital              4441
insurance_provider    4442
billing_amount        4440
room_number           4441
admission_type        4440
discharge_date        4441
medication            4440
test_results          4440
dtype: int64

In [892]:
# Proper case
df['name'] = df['name'].str.title()

In [893]:
df['name'].value_counts()

name
Michael Williams     23
Robert Smith         22
Michael Smith        20
James Brown          18
James Smith          17
                     ..
Robert Pierce         1
Gerald Camacho Md     1
Leslie Bryant         1
Lauren Hubbard        1
Gloria Bowen          1
Name: count, Length: 37683, dtype: int64

In [894]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,NaN,30.0,M,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,M,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,M,B+,HYPERTENSION,02/21/2022,Cassandra Montoya ##,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,M,A+,HYPERTENSION,23-10-19,Eric Martinez ##,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,M,O--,OBESITY,20-12-19,Daryl Mckinney ##,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020.01.05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024.03.21,Justin Wolfe ##,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04/19/2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07/18/2019,Roy Perkins ##,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,NaN,Penicillin,N

In [895]:
# replace "M":"male" and "F":"female"
df['gender'] = df['gender'].replace({"M":"male","F":"female"})

In [896]:
df['gender'].value_counts()

gender
male      25605
FEMALE    25460
Name: count, dtype: int64

In [897]:
# Proper case
df['gender'] = df['gender'].str.title()

In [898]:
df['gender'].value_counts()

gender
Male      25605
Female    25460
Name: count, dtype: int64

In [899]:
df.head()

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,NaN,30.0,Male,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,NaN,28.0,Female,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn

In [900]:
# type change string
df['date_of_admission'] = df['date_of_admission'].astype(str)
df['discharge_date'] = df['discharge_date'].astype(str)

In [901]:
# In both column 'date_of_admission' and 'discharge_date' change dot "." to minus "-" and change slas "/" to minus "-"

df['date_of_admission'] = df['date_of_admission'].str.replace(".","-",regex=False)
df['date_of_admission'] = df['date_of_admission'].str.replace("/","-",regex=False)
df['discharge_date'] = df['discharge_date'].str.replace(".","-",regex=False)
df['discharge_date'] = df['discharge_date'].str.replace("/","-",regex=False)

In [902]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,NaN,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,NaN,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya ##,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez ##,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney ##,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe ##,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins ##,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [903]:
# replace ## in doctor coulmn
df['doctor'] = df['doctor'].str.replace("#",'')

In [904]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,NaN,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,NaN,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [905]:
# replace ,, in hospital coulmn
df['hospital'] = df['hospital'].str.replace(",","")

In [906]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,NaN,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,NaN,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [907]:
df['doctor'].duplicated().sum()

np.int64(17685)

In [908]:
df['doctor'].value_counts()

doctor
Michael Smith       24
John Smith          21
Michael Johnson     20
Robert Smith        19
James Smith         18
                    ..
Brian Hamilton       1
Samantha Cooper      1
Joel Freeman         1
Cynthia Collins      1
Gary Leblanc         1
Name: count, Length: 37819, dtype: int64

In [909]:
# Check the the iteam inside the column
df['insurance_provider'].unique()

array(['Blue Cross', 'Medicare', 'Aetna', nan, 'UnitedHealthcare',
       'Cigna'], dtype=object)

In [910]:
# give space between two words
df['insurance_provider'] = df['insurance_provider'].str.replace("H"," H")

In [911]:
df['insurance_provider'].unique()

array(['Blue Cross', 'Medicare', 'Aetna', nan, 'United Healthcare',
       'Cigna'], dtype=object)

In [912]:
# Check missing values
df.isna().sum()

name                  4440
age                   4440
gender                4440
blood type            4440
medical_condition     4440
date_of_admission        0
doctor                4440
hospital              4441
insurance_provider    4442
billing_amount        4440
room_number           4441
admission_type        4440
discharge_date           0
medication            4440
test_results          4440
dtype: int64

In [913]:
# Data fill in blank cell
df['name'] = df['name'].fillna('Unknown')
df['age'] = df['age'].fillna(df['age'].mean())

In [914]:
df.head(10)

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Unknown,30.000000,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.000000,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.000000,Female,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,Unknown,28.000000,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.000000,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn
5,Unknown,36.000000,Male,A+,ASTHMA,2023-12-20,Taylor Newton,Nunez-Humphrey,United Healthcare,48145.11095104189 USD,389.0,Urgent,2023-12-24,Ibuprofen,N
6,Edward Edwards,21.000000,Female,AB-,DIABETES,11-03-20,Kelly Olson,Group Middleton,Medicare,19580.87234486093 USD,389.0,Emergency,15-11-20,Paracetamol,unknown
7,Christina Martinez,51.576207,NaN,A++,NaN,2021-12-28,Suzanne Thomas,Powell Robinson and Valdez,Cigna,45820.46272159459 USD,277.0,NaN,01-07-22,NaN,unknown
8,Jasmine Aguilar,82.000000,Male,AB+-,NaN,01-07-20,Daniel Ferguson,Sons Rich and,Cigna,50119.222791548505 USD,316.0,Elective,07-14-2020,Aspirin,abn
9,Christopher Berg,58.000000,Female,AB-+,CANCER,2021-05-23,Heather Day,NaN,United Healthcare,NaN,249.0,Elective,22-06-21,Paracetamol,unknown

In [915]:
df['gender'].value_counts()

gender
Male      25605
Female    25460
Name: count, dtype: int64

In [916]:
df['gender'].value_counts().index[0]

'Male'

In [917]:
# Fill in blank cell in gender column
# Here i am using mode() means 'male' or 'female' too many times
# I am check Male 25605 and Female    25460 
# Here index male = o and female = 1 so, i am using [0]

df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

In [918]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,Unknown,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [919]:
# Check gender column
df['gender'].value_counts()

gender
Male      30045
Female    25460
Name: count, dtype: int64

In [920]:
# Check blood type column
df['blood type'].value_counts()

blood type
A-      1670
O+      1650
B-      1644
O-      1639
A+      1637
AB-     1627
B-+     1620
AB+-    1619
AB-+    1618
A+-     1618
AB+     1613
B+-     1613
B-      1605
A-      1603
B+      1597
B++     1588
A--     1586
B+      1582
AB++    1582
O++     1579
A+      1576
A++     1572
AB+     1571
A-+     1569
B--     1569
AB-     1567
O--     1565
AB--    1565
O+-     1562
O+      1557
O-+     1556
O-      1546
Name: count, dtype: int64

In [921]:
# Fill in the blanks blood type column
# Using mode() means which one is repeat too much time that's value fill
df['blood type'] = df['blood type'].fillna(df['blood type'].mode()[0])

In [922]:
df['blood type'].value_counts()

blood type
A-      6110
O+      1650
B-      1644
O-      1639
A+      1637
AB-     1627
B-+     1620
AB+-    1619
AB-+    1618
A+-     1618
AB+     1613
B+-     1613
B-      1605
A-      1603
B+      1597
B++     1588
A--     1586
B+      1582
AB++    1582
O++     1579
A+      1576
A++     1572
AB+     1571
A-+     1569
B--     1569
AB-     1567
O--     1565
AB--    1565
O+-     1562
O+      1557
O-+     1556
O-      1546
Name: count, dtype: int64

In [923]:
df['doctor'].value_counts()

doctor
Michael Smith       24
John Smith          21
Michael Johnson     20
Robert Smith        19
James Smith         18
                    ..
Brian Hamilton       1
Samantha Cooper      1
Joel Freeman         1
Cynthia Collins      1
Gary Leblanc         1
Name: count, Length: 37819, dtype: int64

In [924]:
# Fill the blanks in doctor columns
df['doctor'] = df['doctor'].fillna('Uknown')

In [925]:
df['doctor'].value_counts()

doctor
Uknown              4440
Michael Smith         24
John Smith            21
Michael Johnson       20
Robert Smith          19
                    ...
Brian Hamilton         1
Samantha Cooper        1
Joel Freeman           1
Cynthia Collins        1
Gary Leblanc           1
Name: count, Length: 37820, dtype: int64

In [926]:
df['medical_condition'].value_counts()

medical_condition
ARTHRITIS       8598
DIABETES        8574
HYPERTENSION    8507
OBESITY         8497
ASTHMA          8459
CANCER          8430
Name: count, dtype: int64

In [927]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition     4440
date_of_admission        0
doctor                   0
hospital              4441
insurance_provider    4442
billing_amount        4440
room_number           4441
admission_type        4440
discharge_date           0
medication            4440
test_results          4440
dtype: int64

In [928]:
# Fill 'Unknown' in medical_condition column
df['medical_condition'] = df['medical_condition'].fillna('Unknown')

In [929]:
df['medical_condition'].value_counts()

medical_condition
ARTHRITIS       8598
DIABETES        8574
HYPERTENSION    8507
OBESITY         8497
ASTHMA          8459
CANCER          8430
Unknown         4440
Name: count, dtype: int64

In [930]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital              4441
insurance_provider    4442
billing_amount        4440
room_number           4441
admission_type        4440
discharge_date           0
medication            4440
test_results          4440
dtype: int64

In [931]:
df['hospital'].value_counts()

hospital
LLC Smith                    38
Smith Ltd                    36
Ltd Smith                    36
Smith Group                  34
Johnson Inc                  33
                             ..
Glover-Sawyer                 1
Hernandez and Lee Carr        1
Morris-Brady                  1
and Hayes Williams Walker     1
Jackson Todd and Castro       1
Name: count, Length: 37356, dtype: int64

In [932]:
# Fill 'Unknown' in hospital column
df['hospital'] = df['hospital'].fillna('Unknown')

In [933]:
df['hospital'].value_counts()

hospital
Unknown                      4441
LLC Smith                      38
Ltd Smith                      36
Smith Ltd                      36
Smith Group                    34
                             ...
Glover-Sawyer                   1
Hernandez and Lee Carr          1
Morris-Brady                    1
and Hayes Williams Walker       1
Jackson Todd and Castro         1
Name: count, Length: 37357, dtype: int64

In [934]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider    4442
billing_amount        4440
room_number           4441
admission_type        4440
discharge_date           0
medication            4440
test_results          4440
dtype: int64

In [935]:
df['insurance_provider'].value_counts()

insurance_provider
Cigna                10361
United Healthcare    10247
Medicare             10241
Blue Cross           10192
Aetna                10022
Name: count, dtype: int64

In [936]:
df['insurance_provider'] = df['insurance_provider'].fillna('Unknown')

In [937]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,Uknown,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-22,Aspirin,N
3,Unknown,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317813937623 USD,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381722682367 USD,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [938]:
# Change type
df['billing_amount'] = df['billing_amount'].astype(str)

In [939]:
# Replace USD to blank
df['billing_amount'] = df['billing_amount'].str.replace(" USD","")

In [940]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,Uknown,Cook PLC,Aetna,27955.096078842456,205.0,Emergency,07-10-22,Aspirin,N
3,Unknown,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317813937623,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381722682367,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.9788574008,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.88736491442,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194,NaN,Emergency,nan,Penicillin,N

In [941]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider       0
billing_amount           0
room_number           4441
admission_type        4440
discharge_date           0
medication            4440
test_results          4440
dtype: int64

In [942]:
# Change type
df['billing_amount'] = df['billing_amount'].astype(float)

In [943]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider       0
billing_amount        4440
room_number           4441
admission_type        4440
discharge_date           0
medication            4440
test_results          4440
dtype: int64

In [944]:
# fill in blank space mean()
df['billing_amount'] = df['billing_amount'].fillna(df['billing_amount'].mean())

In [945]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-24,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-19,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,Uknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-22,Aspirin,N
3,Unknown,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-22,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-22,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-19,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,NaN,Emergency,nan,Penicillin,N

In [946]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider       0
billing_amount           0
room_number           4441
admission_type        4440
discharge_date           0
medication            4440
test_results          4440
dtype: int64

In [947]:
df['medication'].value_counts()

medication
Lipitor        10281
Ibuprofen      10245
Aspirin        10205
Paracetamol    10167
Penicillin     10167
Name: count, dtype: int64

In [948]:
# Fill 'Unknown' in medication column
df['medication'] = df['medication'].fillna('Unknown')

In [949]:
df['medication'].value_counts()

medication
Lipitor        10281
Ibuprofen      10245
Aspirin        10205
Paracetamol    10167
Penicillin     10167
Unknown         4440
Name: count, dtype: int64

In [950]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider       0
billing_amount           0
room_number           4441
admission_type        4440
discharge_date           0
medication               0
test_results          4440
dtype: int64

In [951]:
# Check the value inside the column
df['test_results'].value_counts()

test_results
abn        17123
N          17039
unknown    16903
Name: count, dtype: int64

In [952]:
# Fill 'Unkown' in 'test_results' column
df['test_results'] = df['test_results'].fillna('Unknown')

In [953]:
# Check null value
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider       0
billing_amount           0
room_number           4441
admission_type        4440
discharge_date           0
medication               0
test_results             0
dtype: int64

In [954]:
df['test_results'].value_counts()

test_results
abn        17123
N          17039
unknown    16903
Unknown     4440
Name: count, dtype: int64

In [955]:
# Replace value
df['test_results'] = df['test_results'].str.replace("u","U")

In [956]:
df['test_results'].value_counts()

test_results
Unknown    21343
abn        17123
N          17039
Name: count, dtype: int64

In [957]:
# Replace or change name in abn as abnormalanf N means normal
df['test_results'] = df['test_results'].str.replace('abn','Abnormal')
df['test_results'] = df['test_results'].str.replace('N','Normal')

In [958]:
df['test_results'].value_counts()

test_results
Unknown     21343
Abnormal    17123
Normal      17039
Name: count, dtype: int64

In [959]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider       0
billing_amount           0
room_number           4441
admission_type        4440
discharge_date           0
medication               0
test_results             0
dtype: int64

In [960]:
# Fill Not Assigned in room_number
df['room_number'] = df['room_number'].fillna('not assigned')

In [961]:
df.isnull().sum()

name                     0
age                      0
gender                   0
blood type               0
medical_condition        0
date_of_admission        0
doctor                   0
hospital                 0
insurance_provider       0
billing_amount           0
room_number              0
admission_type        4440
discharge_date           0
medication               0
test_results             0
dtype: int64

In [962]:
# Check the value counts inside the admission_type
df['admission_type'].value_counts()

admission_type
Elective     17189
Urgent       17056
Emergency    16820
Name: count, dtype: int64

In [963]:
# Fill Unknown in the  blank 
df['admission_type'] = df['admission_type'].fillna('Unknown')

In [964]:
df.isnull().sum()

name                  0
age                   0
gender                0
blood type            0
medical_condition     0
date_of_admission     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
discharge_date        0
medication            0
test_results          0
dtype: int64

In [965]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55505 entries, 0 to 55504
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                55505 non-null  object
 1   age                 55505 non-null  float64
 2   gender              55505 non-null  object
 3   blood type          55505 non-null  object
 4   medical_condition   55505 non-null  object
 5   date_of_admission   55505 non-null  object
 6   doctor              55505 non-null  object
 7   hospital            55505 non-null  object
 8   insurance_provider  55505 non-null  object
 9   billing_amount      55505 non-null  float64
 10  room_number         55505 non-null  object
 11  admission_type      55505 non-null  object
 12  discharge_date      55505 non-null  object
 13  medication          55505 non-null  object
 14  test_results        55505 non-null  object
dtypes: float64(2), object(13)
memory usage: 6.4+ MB

In [966]:
# Change type in date_of_admission
df['date_of_admission'] = df['date_of_admission'].astype(str)

In [967]:
# space remove using strip() function
df['date_of_admission'] = df['date_of_admission'].str.strip()

In [968]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-24,Paracetamol,Normal
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-19,Ibuprofen,Unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,Uknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-22,Aspirin,Normal
3,Unknown,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-22,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-22,Ibuprofen,Unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-19,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-19,Paracetamol,Unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-19,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,Abnormal
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,Unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,not assigned,Emergency,nan,Penicillin,Normal

In [969]:
# Change type in discharge_date
df['discharge_date'] = df['discharge_date'].astype(str)

In [970]:
# space remove using strip() function
df['discharge_date'] = df['discharge_date'].str.strip()

In [971]:
dates = pd.to_datetime(df['date_of_admission'],errors="coerce")

In [972]:
df['date_of_admission'] = dates

In [973]:
mask = dates.isna()

In [974]:
mask

0        False
1        False
2         True
3         True
4        False
         ...
55500     True
55501     True
55502     True
55503    False
55504     True
Name: date_of_admission, Length: 55505, dtype: bool

In [975]:
dates[mask] = pd.to_datetime(df.loc[mask,"date_of_admission"],errors="coerce",dayfirst=True)

In [976]:
df['date_of_admission'] = dates

In [977]:
df['date_of_admission'].fillna(df['date_of_admission'].median(),inplace=True)

In [978]:
df

,name,age,gender,blood type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-24,Paracetamol,Normal
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-19,Ibuprofen,Unknown
2,Danny Smith,76.0,Female,A-,OBESITY,2021-10-23,Uknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-22,Aspirin,Normal
3,Unknown,28.0,Female,O+,DIABETES,2021-10-23,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-22,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,2021-10-23,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-22,Ibuprofen,Unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,2021-10-23,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-19,Paracetamol,Unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,2021-10-23,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,Abnormal
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,Unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,2021-10-23,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,not assigned,Emergency,nan,Penicillin,Normal

In [979]:
dates = pd.to_datetime(df['discharge_date'],errors="coerce")

In [980]:
df['discharge_date'] = dates

In [981]:
mask = dates.isna()

In [982]:
dates[mask] = pd.to_datetime(df.loc[mask,"discharge_date"],errors="coerce",dayfirst=True)

In [983]:
df['discharge_date'].fillna(df['discharge_date'].median(),inplace=True)

In [984]:
#discharge_date
       ↓
#Convert to date format
       ↓
#Invalid dates → NaT
       ↓
#Try DD/MM/YYYY conversion
       ↓
#Find median date
       ↓
#Replace missing dates with median

# If your column contains dates in different formats, a better approach is to inspect the original data first. 
#For example:
#df['discharge_date'] = pd.to_datetime(
#    df['discharge_date'],
#    errors='coerce',
 #   dayfirst=True
#)

# df['discharge_date'] = df['discharge_date'].fillna(
#  df['discharge_date'].median()
#)

IndentationError: unexpected indent (2240405141.py, line 2)

In [ ]:
df

In [ ]:
# Change type blood type to string
df['blood type'] = df['blood type'].astype(str)

In [ ]:
df['blood type'] = df['blood type'].str.strip()

In [ ]:
df['blood type'] = df['blood type'].str.upper()

In [ ]:
df

In [ ]:
# replace +-, -+, --, ++ using lambda
df['blood type'] = df['blood type'].str.replace(r"(\+|-)+$",lambda x: x.group(0)[0].upper(),regex=True)

In [ ]:
df

In [ ]:
df['blood type'].value_counts()

In [ ]:
df.info()

In [ ]:
# Correct decimal places using round() functiom
df['billing_amount'] = df['billing_amount'].round(2)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df.to_excel("Hospital_data_cleaned.xlsx",index=False)